############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
weight = 2
name = "Blog"

[[main]]
parent = "Blog"
name = "View"
url = "/blog"

[[main]]
parent = "Blog"
name = "Authors"
url = "/authors"

[[main]]
parent = "Blog"
name = "Categories"
url = "/categories"

[[main]]
name = "About"
url = "/about"
weight = 3

[[main]]
name = "Contact"
url = "/contact"
weight = 4

# footer menu
[[footer]]
name = "About"
url = "/about"
weight = 1

[[footer]]
name = "Elements"
url = "/elements"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 3
